import sqlite3
conn=sqlite3.connect('practice.db')
cursor=conn.cursor()
cursor.execute("insert into students values (4,'asiya',22,92)")
cursor.execute("insert into students values (5,'alex',24,91)")
cursor.execute("insert into students values (6,'amina',25,60)")
cursor.execute("select * from students")
result=cursor.fetchall()
print(result)
cursor.execute("select name from students where marks>60")
res=cursor.fetchall()
print(res)
cursor.execute("select * from students where age>=20")
re=cursor.fetchall()
print(re)
cursor.execute("select name from students where age<21 and marks>70")
r=cursor.fetchall()
print(r)
cursor.execute("select * from students where marks>200")
ma=cursor.fetchall()
print(ma)
cursor.execute("select * from students")
print(cursor.fetchall())